---
- name: Disable swap
  command: swapoff -a
  become: true

- name: Ensure swap is disabled in fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    state: absent
  become: true

- name: Load necessary kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  become: true

- name: Apply sysctl settings
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  become: true

- name: Reload sysctl settings
  command: sysctl --system
  become: true